# Generated by Django 3.2.6 on 2021-08-14 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210814_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='place',
            name='complement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='place',
            name='district',
            field=models.CharField(max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='place',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='place',
            name='parent_company',
            field=models.CharField(max_length=100, verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place',
            field=models.CharField(max_length=100, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='place',
            name='state',
            field=models.CharField(max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='recyclingcenter',
            name='place',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.place'),
        ),
    ]
