# Generated by Django 3.2.6 on 2021-08-14 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_place_place_place_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(blank=True, null=True)),
                ('confirmed', models.BooleanField()),
                ('added_points', models.PositiveIntegerField(default=0)),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.donnor')),
                ('recyclingCenter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recyclingcenter')),
            ],
        ),
        migrations.CreateModel(
            name='RecyclabelMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('quatity', models.PositiveIntegerField()),
                ('donation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.donation')),
            ],
        ),
    ]
