# Generated by Django 3.2.6 on 2021-08-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_donation_recyclabelmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='confirmed',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='recyclabelmaterial',
            name='quatity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
