# Generated by Django 3.2.6 on 2021-08-22 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210820_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclabelmaterial',
            name='quatity',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Attending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('date_attending', models.DateTimeField()),
                ('obs', models.TextField(max_length=500)),
                ('status_attending', models.CharField(choices=[('CA', 'Confirmado atendimento'), ('AG', 'Aguardando confirmação'), ('CC', 'Cancelado')], max_length=2)),
                ('confirmed', models.BooleanField(blank=True, default=None, null=True)),
                ('return_recipient', models.TextField(max_length=300)),
                ('points_attending', models.TextField(default=0)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recyclingcenter')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.donnor')),
            ],
        ),
    ]
