# Generated by Django 3.2.6 on 2021-08-24 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='attending',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.attending'),
        ),
    ]
