# Generated by Django 3.2.6 on 2021-08-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_donation_attending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attending',
            name='status_attending',
            field=models.CharField(choices=[('CA', 'Confirmado atendimento'), ('AG', 'Aguardando confirmação'), ('CC', 'Cancelado'), ('AD', 'Aguardando confirmação de Doação'), ('CD', 'Concluído')], max_length=2),
        ),
    ]
