# Generated by Django 3.2.6 on 2021-08-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_attending_status_attending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='confirmed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
